### ISSUE TITLE
Functionalizing density plot creation 

### ISSUE THREAD

**Issue by pmaji** [pmaji/data-science-toolkit#8]
@ndrewGele is going to put together a PR that involves a functionalized solution for density plot creation to supplement the md on the KS test here:

https://github.com/pmaji/data-science-toolkit/blob/master/hypothesis-tests/ks_test.md

**Comment by ndrewGele** [comment]
Data isn't in the directory. Is it ignored or not added?

**Comment by pmaji** [comment]
Ah I might not have changed the path over appropriately. I’ll check this out in ~45 min when I’m back home: 

*******
Paul Jeffries
LinkedIn
Sent from my iPhone 
(Please excuse any typos)

**Comment by pmaji** [comment]
@ndrewGele -- data have been added to the directory. If you git pull should work fine. Let me know if that's not the case.

**Comment by pmaji** [comment]
Ah... and now I remember why I didn't put the data there the first time. It's a really big file that's over the 50 mb recommended limit. So it's there, but in the future I might do something else with it... Maybe I'll zip it or run a rsample on it to trim it down.

**Comment by pmaji** [comment]
Ok, the size thing irked me too much so I sampled it by 50% and deleted the big file in a PR just now. 

So everything remains the same, except now the file you should use it:

"hypothesis-tests/data/ks-projects-201801-sampled.csv"

**Comment by pmaji** [comment]
@ndrewGele I made one change after looking it over more precisely -- there was an area where adding two more quo'ed vars made the thing more parameterizable, so you'll see that in the commit history :)

Thanks for your help with this! Super helpful contribution. I'm excited to use this thing a lot more
